lib/accounts_receivable_phoenix_web/router.ex
defmodule AccountsReceivablePhoenixWeb.Router do
  use AccountsReceivablePhoenixWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", AccountsReceivablePhoenixWeb do
    pipe_through :browser

    get "/", InvoiceController, :index
    resources("/clients", ClientController)
    resources("/invoices", InvoiceController)
    resources("/line_items", LineItemController)
    resources("/products", ProductController)
    resources("/services", ServiceController)
  end

  # Other scopes may use custom stacks.
  # scope "/api", AccountsReceivablePhoenixWeb do
  #   pipe_through :api
  # end
end

lib/accounts_receivable_phoenix_web/views/layout_view.ex
defmodule AccountsReceivablePhoenixWeb.LayoutView do
  use AccountsReceivablePhoenixWeb, :view
end

lib/accounts_receivable_phoenix_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>AccountsReceivablePhoenix · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/assets/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><%= link "Clients", to: Routes.client_path(@conn, :index) %></li>
            <li><%= link "Products", to: Routes.product_path(@conn, :index) %></li>
            <li><%= link "Services", to: Routes.service_path(@conn, :index) %></li>
            <li><%= link "Invoices", to: Routes.invoice_path(@conn, :index) %></li>
            <li><%= link "Invoice Line Items", to: Routes.line_item_path(@conn, :index) %></li>
          </ul>
        </nav>
        <a href="/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Frameork Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/assets/app.js") %>"></script>
  </body>
</html>